PSLmodels/ParamTools

paramtools/parameters.py
paramtools/tests/test_weather_ex.py

This PR adds a method for querying all parameters.
```python
In [2]: from paramtools import parameters
...: from paramtools.utils import get_example_paths
...: 
...: # example weather parameters
...: project_schema, baseline_parameters = get_example_paths('weather')
...: 
...: class WeatherParams(parameters.Parameters):
...:     project_schema = project_schema
...:     baseline_parameters = baseline_parameters
...: 
...: params = WeatherParams()
...: 
...: 
In [3]: 
In [3]: params.get_all(month="November")
Out[3]: 
{'average_high_temperature': [{'value': 59,
'month': 'November',
'city': 'Washington, D.C.',
'dayofmonth': 1},
{'value': 64, 'month': 'November', 'city': 'Atlanta, GA', 'dayofmonth': 1}],
'average_precipitation': [{'value': 3.0,
'month': 'November',
'city': 'Washington, D.C.'}, …
```

Add method for getting all parameters

---

paramtools/build_schema.py
paramtools/parameters.py
paramtools/tests/test_tc_ex.py
paramtools/tests/test_utils.py
paramtools/tests/test_weather_ex.py
paramtools/utils.py

`marshmallow` returns a dictionary of error messages which corresponds to the structure of the inputs dictionary. Thus, if the inputs dictionary was:
```python
{
"inputs": ["good value", "bad value"],
}
```
the error dictionary would be something like:
```python
{
"inputs": {1: "'bad value' not allowed!"} ,
}
```
This is somewhat helpful if you know how the inputs dictionary is structured. However, there are other situations where you don't really care what the inputs dictionary looks like--you just want the error messages.
One implementation comment that I noted int he `LeafGetter` docstring, a functional approach was considered instead of using a class. However, I was unable to come up with a way to store all of the leaves without "cheating" and keeping "leaf" state. In the future, I …

Pull all error messages from error dictionary 

---

paramtools/parameters.py
paramtools/tests/test_all.py
paramtools/tests/test_weather_ex.py

This PR changes the following two methods:
- `get`: This method is used to retrieve the value of a single parameter. The user can filter the "value" list by querying along zero or more allowed dimensions. If the dimension that is queried does not exist in the value list, a `KeyError` exception is thrown. Considering the following parameter:
```json
"min_int_param": {
"value": [
{"dim0": "zero", "dim1": 1, "value": 1},
{"dim0": "one", "dim1": 2, "value": 2}
],
}
```
`params.get('min_int_param', dim0="zero")` returns `[{"dim0": "zero", "dim1": 1, "value": 1}]`, but `params.get('min_int_param', notadim="abc")` throws a `KeyError` because `notadim` is not an allowed dimension.
- `specification`: This method is used to retrieve the value of all parameters. The user can filter these values by …

Refinements to get and specifications methods

---

README.md
examples/baseball/schema.json
examples/taxcalc/schema.json
examples/weather/schema.json
paramtools/schema.py
paramtools/tests/schema.json

I recently re-discovered the [Mozilla WOT API][1] spec and was really taken with how clean their JSON schema docs were. They define JSON objects and properties and they link to their definitions when they are used in a given schema. This has the benefit of abstracting away some of the low-level information that you don't need to understand fully right off the bat. 
For example, the `defaults.json` file is a mapping of parameter names to their meta data--that's it. Then, you can dive deeper into the Parameter objects. You find out that they are composed of some properties, a list of Value objects, and a mapping of Validator objects. Then, when it's time, one can take a look at those objects.
This way users can take information in one layer at a time--without being hit by a wall of …

Docs re-organization

---

.travis.yml
README.md
examples/weather/defaults.json
paramtools/parameters.py
paramtools/schema.py
paramtools/tests/defaults.json
paramtools/tests/schema.json
paramtools/tests/test_all.py
paramtools/tests/test_weather_ex.py

This PR adds `to_array` and `from_array` methods to the `Parameters` class. See the updated README for example usage:
I went back and forth about what to name the methods. Other options I considered are:
- `array` instead of `to_array`. as in `params.array("some_param")`
- `valueobjects` instead of `from_array`. as in `params.valueobjects("some_param", array)`
I'm interested in hearing feedback on the method names.
An Order object is added to the JSON schema by this PR. It supplies information about the dimension space of a particular parameter:
- "dim_order": order of the axes of the array. 
- "value_order": expected values of the dimensions and the order of those values along the given dimension.
This information is used to construct the shape of the array and its indexing.

Add methods for converting to and from arrays

---

.pre-commit-config.yaml
.travis.yml
paramtools/__init__.py
paramtools/contrib/__init__.py
paramtools/contrib/validate.py
paramtools/schema.py
paramtools/tests/test_all.py
paramtools/tests/test_baseball.py
paramtools/tests/test_tc_ex.py
paramtools/tests/test_utils.py
paramtools/tests/test_weather_ex.py
pyproject.toml
requirements-dev.txt

This PR adds:
- `requirements-dev.txt`: installs black, pre-commit, numpy, and pytest.
- numpy is still not absolutely required, but users who do not install numpy will not have access to the `to_array`/`from_array` methods. 
- Use pre-commit to automatically re-format code on commit. i.e. black formats your code so *you* don't have to.
- Import all packages to `__init__.py` modules. This allows the user to do:
```python
from paramtools import Parameters
```
whereas they had to do this before:
```python
from paramtools.parameters import Parameters
```

Improve development/user experience

---

.pre-commit-config.yaml
paramtools/contrib/validate.py
paramtools/schema.py
paramtools/tests/test_all.py
paramtools/tests/test_validate.py
pyproject.toml

This PR:
- Adds support for array parameters that use the choice validator.
- Does not display choices if there are more than 20.
- Another option for displaying this data is to display the first 10 or 20 choices. I made this change because Matchups uses a list of 20,000 choices (every Major League Baseball player ever). It was absurd to display all of them. I didn't think displaying the first N choices would add more information. However, I'm open to discussing this further:
```python
In [1]: import matchups
In [2]: params = matchups.MatchupsParams()
In [3]: params.adjust({"batter": [{"value": ["not a real better"], "use_2018": False}]})
...
ValidationError: {'batter': ['batter "not a real better" must be in list of choices for dimensions use_2018=False.']}
In [4]: 
```

Add a OneOf contrib class to support array params

---

.pre-commit-config.yaml
paramtools/exceptions.py
paramtools/parameters.py
paramtools/tests/test_all.py

This PR:
- Fixes a bug where an error was raised if the `errors` property was called with no errors present.
- Links the dimension values for a Value object that causes an error to the corresponding parameter name

Fix bugs around error messages

---

paramtools/parameters.py
paramtools/schema.py
requirements-dev.txt
setup.py

Prior to this PR, ParamTools could be used without NumPy. However, ParamTools is going to need powerful array manipulation functionality and NumPy provides that.

Make NumPy a hard dependency

---

README.md
paramtools/contrib/__init__.py
paramtools/contrib/fields.py
paramtools/contrib/validate.py
paramtools/exceptions.py
paramtools/parameters.py
paramtools/schema.py
paramtools/tests/defaults.json
paramtools/tests/test_all.py
paramtools/tests/test_fields.py
paramtools/tests/test_utils.py
paramtools/utils.py

This PR makes it possible to use the `Parameters.to_array` and `Parameters.from_array` methods without specifying an [order object][1]. This is accomplished by inspecting the dimension validators set in `schema.json`. The order of the dimensions is set by the order that the dimensions are specified in `schema.json`. The values that those dimensions can take on are determined by inspecting the validator object. The choice validator's values are set in the "choices" attribute. The range validator's values are determined by generating a list of values from the min to the max value, incrementing by one. In a future PR, a "step" or "increment" value will be added.
For example, consider the weather parameters:
```json
"dims": {
"city": {
"type": "str",
"validators": {"choice": {"choices": …
```

Use dimension validator information in to/from_array methods

---

paramtools/tests/test_examples/test_baseball.py
paramtools/tests/test_examples/test_tc_ex.py
paramtools/tests/test_examples/test_weather_ex.py

This PR moves the tests for the examples config files to a submodule `test_examples`.

Move example tests to submodule

---

paramtools/examples/behresp/defaults.json
paramtools/examples/behresp/schema.json
paramtools/parameters.py
paramtools/schema.py
paramtools/tests/test_examples/test_behresp.py
paramtools/tests/test_parameters.py
paramtools/utils.py

This PR adds example parameters for the Behavior-Responses package per @martinholmer's suggestion in #34. I also made a couple minor changes to clean things up while I was testing out this example.
```
(paramtools-dev) henrydoupe@henry-mac:~/Documents/ParamTools$ cd paramtools/examples/behresp/
(paramtools-dev) henrydoupe@henry-mac:~/Documents/ParamTools/paramtools/examples/behresp$ ipython
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from paramtools import Parameters 
...:  
...: class BehrespParams(Parameters): 
...:     schema = "schema.json" 
...:     defaults = "defaults.json" 
...:     array_first = True 
...: …
```

Add example with Behresp parameters

---

paramtools/contrib/validate.py
paramtools/parameters.py
paramtools/schema.py
paramtools/tests/test_parameters.py

This PR adds the ability to delete existing value objects by setting their value to `None`. For example,
```python
In [1]: from paramtools import Parameters                                                                                                                                                                                                                                       
In [2]: class TaxParams(Parameters): 
...:     schema = "taxparams-demo/schema.json" 
...:     defaults = "taxparams-demo/defaults.json" 
...:                                                                                                                                                                                                                                                                         
In …
```

Add ability to delete existing value objects

---

README.md
docs/source/readme.rst
paramtools/__init__.py
paramtools/exceptions.py
paramtools/parameters.py
paramtools/tests/test_parameters.py

This PR resolves a bug reported by @Peter-Metz. He included a variable named "state" in his `defaults.json` file. The `Parameters` class set that variable as the attribute `state`. However, `state` is already used by `ParamTools` to keep track of the dimension state. This PR renames `state` to `_state`. It shouldn't be changed directly by the user anyways. It can still be viewed via the `view_state` and as before, it should be updated through `set_state`. This PR also adds a list of variable names that are used by `Parameters`. An exception is raised when the user tries to use a name that is already used by `Parameters`:
```
In [1]: from paramtools import Parameters …
```

Parameter name collision bug

---

.pre-commit-config.yaml
paramtools/build_schema.py
paramtools/examples/baseball/defaults.json
paramtools/examples/baseball/schema.json
paramtools/examples/behresp/defaults.json
paramtools/examples/taxparams-demo/defaults.json
paramtools/examples/taxparams/schema.json
paramtools/examples/weather/defaults.json
paramtools/examples/weather/schema.json
paramtools/schema.py
paramtools/tests/defaults.json
paramtools/tests/schema.json
paramtools/tests/test_parameters.py

See #43.
With this change, one can do an adjustment via:
```python
In [1]: import paramtools 
...: class Params(paramtools.Parameters): 
...:     schema = "paramtools/tests/schema.json" 
...:     defaults = "paramtools/tests/defaults.json" 
...: params = Params() 
...:                                                                                                                       
In [2]: params.int_default_param                                                                                              
Out[2]: [{'value': 2}]
In [3]: params.adjust({ 
...:     "int_default_param": 4, 
...: })                                                                                                                    
In [4]: params.int_default_param …
```

Make it simple to work with simple parameters 

---

README.md
docs/markdown/spec.md
docs/source/readme.rst
docs/source/spec.rst
paramtools/__init__.py
paramtools/build_schema.py
paramtools/contrib/fields.py
paramtools/contrib/validate.py
paramtools/examples/baseball/schema.json
paramtools/examples/behresp/schema.json
paramtools/examples/taxparams-demo/schema.json
paramtools/examples/taxparams/schema.json
paramtools/examples/weather/schema.json
paramtools/exceptions.py
paramtools/parameters.py
paramtools/schema.py
paramtools/tests/defaults.json
paramtools/tests/schema.json
paramtools/tests/test_fields.py
paramtools/tests/test_parameters.py
paramtools/tests/test_utils.py
paramtools/tests/test_validate.py
paramtools/utils.py

See #43. This PR renames "dimension" to "label." Label was chosen instead of "selector" because labels--not selectors--are used to describe an entity. Entities are then *selected* based off of their *labels*.

Rename "dimension" to "label"

---

paramtools/build_schema.py
paramtools/tests/test_parameters.py

Fix bug where the `defaults` dictionary was modified on initialization. The "schema" member was removed from the original dictionary. Now, a copy of `defaults`, without the "schema" member, is created on initialization.

Original dict should not be modified

---

paramtools/__init__.py
paramtools/build_schema.py
paramtools/contrib/fields.py
paramtools/exceptions.py
paramtools/parameters.py
paramtools/schema.py
paramtools/tests/test_fields.py
paramtools/tests/test_parameters.py

Adds a `serializable` flag to the `Parameters.specification` method. Some NumPy data types (e.g. `np.bool_`) and types like `datetime`/`date` are not JSON serializable. This functionality is helpful when you want to dump a `Parameters` instance's data to a JSON file or send it over the wire via a web request.
```python
In [1]: import paramtools 
...: path = "paramtools/examples/taxparams-demo/defaults.json" 
...: class Params(paramtools.Parameters): 
...:     defaults = path 
...:                                                                                                                       
In [2]: params = Params()                                                                                                     
In [3]: params.specification(serializable=True, meta_data=True) …
```

Add serializable flag to specification method

---

paramtools/__init__.py
paramtools/parameters.py
paramtools/schema_factory.py

Rename `SchemaBuilder` to `SchemaFactory` since the code follows the [factory design pattern](https://realpython.com/factory-method-python/).

Rename schema 'builder' to schema 'factory'

---

docs/docs/api/extend.md
docs/docs/api/guide.md
docs/mkdocs.yml
paramtools/contrib/fields.py
paramtools/exceptions.py
paramtools/parameters.py
paramtools/schema.py
paramtools/tests/defaults.json
paramtools/tests/test_fields.py
paramtools/tests/test_parameters.py

Partially resolves #56. Parameters can be extended along one label. This is helpful for filling out a parameter's values without having to specify redundant data in `defaults.json`. ParamTools uses label validation data to create a discrete list of values for each label. This is used to figure out which values of `label_to_extend` are missing and the direction in which the values need to be extended.
```python
class Parameters(paramtools.Parameters):
defaults = "converted.json"
label_to_extend = "year"
array_first = True
params = Parameters()
```
Parameter values will be extended along the "year" label with these values:
```python
params.label_grid["year"]
```
Check that EITC_c was extended:
```python
params.EITC_c
```
Documentation for this feature will be added to this …

Extend parameter values along a specified label

---

.pre-commit-config.yaml
README.md
docs/Extend example.ipynb
docs/README Example.ipynb
docs/docs/api/extend.md
docs/docs/index.md
paramtools/__init__.py
paramtools/contrib/fields.py
paramtools/contrib/validate.py
paramtools/exceptions.py
paramtools/parameters.py
paramtools/schema.py
paramtools/select.py
paramtools/tests/extend_ex.json
paramtools/tests/test_parameters.py
paramtools/tests/test_select.py
paramtools/tests/test_utils.py
paramtools/tests/test_validate.py
paramtools/typing.py
paramtools/utils.py

Implementing the extend capability for adjustments exposed some limitations with the [initial approach](https://github.com/PSLmodels/ParamTools/blob/0.6.0/paramtools/parameters.py#L305-L363) in ParamTools 0.6.0. The issue with the initial extend approach was that it was not granular enough. Either all of the allowed label values needed to be defined or none of them could be. The example below exposes this problem:
```python
class TaxParams(paramtools.Parameters):
defaults = {
"schema": {
"labels": {
"year": {
"type": "int",
"validators": {"range": {"min": 2013, "max": 2027}}
},
"marital_status": {
"type": "str",
"validators": {"choice": {"choices": ["single", "joint"]}}
},
}
},
"standard_deduction": {
"title": "Standard deduction amount",
"description": "Amount filing …
```

Make extend method more granular

---

paramtools/parameters.py
paramtools/tests/extend_ex.json
paramtools/tests/test_parameters.py
paramtools/utils.py

Fixes two bugs that were exposed in PSLmodels/Cost-of-Capital-Calculator#269:
- Situation where parameters that do not use `label_to_extend` are adjusted in extend mode. This caused a `KeyError`. For example: 
```python
params = ExtParams()
params.adjust({"nonextend_param": 3})
```
- Situation where a parameter's value is adjusted at a value of `label_to_extend` that is not active in the current state. For example:
```python
In [1]: import paramtools                                                                                                     
In [2]: class ExtParams(paramtools.Parameters): 
...:     defaults = "extend_ex.json" 
...:     array_first = True 
...:     label_to_extend = "d0" 
...: …
```

Fix bugs from CCC #269

---

environment.yml
paramtools/contrib/fields.py
paramtools/contrib/validate.py
paramtools/schema.py
setup.py

Marshmallow a couple [changes to its API](https://marshmallow.readthedocs.io/en/3.0/changelog.html#rc7-2019-06-15):
- Methods decorated with `validates_schema` need to have a `**kwargs` parameter.
- The new range validator error messages use a `max_op` and `min_op` arg for specifying whether the test was strict or not.

Update custom fields for Marshmallow 3.0.0rc7 API changes

---

docs/docs/api/guide.md
docs/docs/api/indexing.md
docs/mkdocs.yml
paramtools/examples/taxparams/defaults.json
paramtools/exceptions.py
paramtools/parameters.py
paramtools/schema.py
paramtools/tests/extend_ex.json
paramtools/tests/test_parameters.py

This PR adds parameter indexing. This is turned on by setting the class attribute `indexed` to `True` and  by implementing an `indexing_rate` method. Here's an example that indexes Tax-Calculator's parameters:
```python
class TaxParams(paramtools.Parameters):
defaults = {
"schema": {
"labels": {
"year": {
"type": "int",
"validators": {"range": {"min": 2013, "max": 2027}}
},
"marital_status": {
"type": "str",
"validators": {"choice": {"choices": ["single", "joint"]}}
},
}
},
"standard_deduction": {
"title": "Standard deduction amount",
"description": "Amount filing unit can use as a standard deduction.",
"type": "float",
"indexed": True,
"value": [
{"year": 2017, "marital_status": "single", "value": 6350},
{"year": 2017, "marital_status": "joint", "value": 12700}, …
```

Add parameter indexing

---

docs/customadjust.py
docs/docs/api/custom-adjust.md
docs/docs/api/guide.md
docs/mkdocs.yml
paramtools/exceptions.py
paramtools/parameters.py

This moves the adjustment logic to a private `_adjust` method, and the `adjust` method simply calls this private method. This makes it easier to write custom `adjust` methods on top of ParamTools which is helpful if a project wants to define its own custom adjustment data format or if it needs to apply custom logic to its adjust method. Without this alias approach, ParamTools's internal methods may accidentally call your wrapper method instead of the core adjust method. The convention for doing this is something like:
```python
import io
import os
import pandas as pd
class CSVParams(paramtools.Parameters):
defaults = {
"schema": {
"labels": {
"year": {
"type": "int", 
"validators": {"range": {"min": 2000, "max": 2005}}
}
}
},
"a": {
"title": "A",
"description": "a …
```

Alias adjust method to make it easy to write custom adjust methods

---

paramtools/parameters.py
paramtools/tests/test_parameters.py

This PR makes a couple enhancements to the extend method:
- Updates all values at once instead of one at a time. This better respects validation that depends on the values of other parameters.
- `extend` takes a `label_to_extend_values` argument allowing you to specify how a parameter's values are extended on a more granular level.

Enhancements and bug fixes for extend method

---

paramtools/exceptions.py
paramtools/parameters.py
paramtools/tests/test_parameters.py

This makes the `Parameters` class iterable. Now, it can be looped over like a dictionary:
```python
class MyParams(paramtools.Parameters):
defaults = {
"one_param": {
"title": "one param",
"description": "",
"type": "str",
"value": "hello"
},
"two_param": {
"title": "two param",
"description": "",
"type": "str",
"value": "world"
}
}
params = MyParams()
for param in params:
print(param)
for param, value in params.items():
print(param, value)
params.keys()

Make Parameters class iterable

---

docs/docs/parameters.md
paramtools/exceptions.py
paramtools/parameters.py
paramtools/schema.py
paramtools/tests/test_parameters.py

Rename "actions" to "operators" in "schema" object. I meant to do this in PR #73 (and indeed [thought that I did](https://github.com/PSLmodels/ParamTools/pull/73#issuecomment-529965975)), but I somehow forgot to push the final commit that did the update.

actions -> operators

---

paramtools/exceptions.py
paramtools/parameters.py
paramtools/tests/test_parameters.py

This PR adds a method for sorting values according to label order as defined in the schema object. Values objects that are added as part of the "extend" process are added randomly and thus, do not appear to have a sensible order. This feature helps applications like Compute Studio that use the order of the value objects for display purposes.

Add method for sorting values according to label order

---

paramtools/parameters.py
paramtools/tests/test_parameters.py

This PR makes `dump` sort the value objects by default. Initially, this was not the default because there is a small performance hit on `dump` when the values are sorted (about 10ms on a large configuration). However, I think the result will be less confusing to users who expect the value objects to have a certain order. Users with performance concerns can simply set `sort_values` to `False`.

Sort values by default in dump()

---

docs/docs/parameters.md
paramtools/contrib/validate.py
paramtools/exceptions.py
paramtools/parameters.py
paramtools/schema.py
paramtools/tests/defaults.json
paramtools/tests/test_parameters.py
paramtools/tests/test_validate.py

Adds a "level" argument to the validators object that allows the user to specify whether it should throw a warning or not if the value is not valid. If level is set to "warning" then a warning is thrown. By default, "level" is set to "error," and does not need to explicitly be specified. Users can control whether warnings are ignored or raised by setting `ignore_warnings` to `True` in the `Parameters.adjust(...)` method. Note that `ignore_warnings` is `False` by default.
```python
class Params(paramtools.Parameters):
defaults = {
"myparam": {
"title": "a param",
"description": "",
"type": "int",
"value": 2,
"validators": {
"range": {"min": 0, "max": 2, "level": "warn"} # <--- level set to warn
}
}
}
```
Throws error when `ignore_warnings` is `False`:
```python
params = …
```

Add warnings

---

docs/docs/parameters.md
paramtools/contrib/__init__.py
paramtools/contrib/validate.py
paramtools/schema.py
paramtools/tests/defaults.json
paramtools/tests/test_parameters.py
paramtools/tests/test_validate.py

Resolves #64. I wound up going with a [style similar to what is used by `yup`](https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema):
```json
"swages": {
"title": "Wage and salary income of spouse",
"description": "Include self-employment",
"type": "float",
"value": 0,
"validators": {
"when": {
"param": "marital_status",
"is": "single",
"then": {
"range": {"min": 0, "max": 0}
},
"otherwise": {
"range": {"min": 0, "max": 9e+99}
}
}
}
}
```
@jdebacker @Peter-Metz does this solve your use cases/do you have any feedback on this PR?

Add 'when' validator

---

paramtools/schema.py
paramtools/schema_factory.py
paramtools/tests/test_parameters.py

PR #72 added strict validation on the "schema" object making it impossible to define custom fields on ParamTools objects. Support for custom fields was added to support fields like Tax-Calculator's `compatible_data`. Since there wasn't a test for this feature, no errors were thrown when it was removed in #72. This PR re-instates this feature and adds a test for custom fields so that this doesn't happen again in the future.
```python
import marshmallow as ma
import paramtools as pt
class CompatibleData(ma.Schema):
cps = ma.fields.Boolean()
puf = ma.fields.Boolean()
class Params(pt.Parameters):
field_map = {"compatible_data_type": ma.fields.Nested(CompatibleData)}
defaults = {
"schema": {
"additional_members": {
"compatible_data": {"type": "compatible_data_type"}
}
},
"standard_deduction": …
```

Bug fix: Bring back support for custom fields

---

docs/docs/api/custom-types.md
docs/docs/api/guide.md
paramtools/__init__.py
paramtools/exceptions.py
paramtools/parameters.py
paramtools/schema.py
paramtools/schema_factory.py
paramtools/tests/test_examples/test_tc_ex.py
paramtools/tests/test_parameters.py
paramtools/tests/test_schema.py

Prompted by the issue that @jdebacker opened, this PR adds the ability to register custom fields like this:
```python
import paramtools as pt
import marshmallow as ma
class DepreciationRules(ma.Schema):
life = ma.fields.Integer(validate=ma.validate.Range(min=0))
method = ma.fields.String(
validate=ma.validate.OneOf(choices=["SL", "Expensing"])
)
pt.register_custom_type("depreciation_rules", ma.fields.Nested(DepreciationRules()))
class AssetsParams(pt.Parameters):
defaults = "assets.json"
```
Using this code, we can load defaults that look like this:
```json
{
"asset": {
"title": "CCC Assets",
"description": "assets param",
"type": "depreciation_rules",
"value": [
{
"value": {
"life": 5,
"method": "SL"
}
},
{
"value": {
"life": 5,
"method": "SL"
}
}
]
}
}
```

Add ability to register custom fields

---

docs/docs/CNAME
docs/docs/api/reference.md
docs/docs/css/custom.css
docs/mkdocs.yml

The PT docs have needed a little TLC for a bit now. This PR adds:
- API reference docs using [`mkautodoc`](https://github.com/tomchristie/mkautodoc)
- New theme using [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)
- Updates to the CSS to use Atlanta Braves blue
- New domain at https://paramtools.dev

Add api-reference, update docs theme and style

---

paramtools/parameters.py
paramtools/tests/test_parameters.py

ParamTools emits warnings if you adjust a parameter's value that is not active. That is, the value's label value is not in the set of values in the active `state`. This PR removes those warnings since this case is more normal than I thought:
```python
In [1]: import taxcalc                                                                                                                                                                        
In [2]: pol = taxcalc.Policy()                                                                                                                                                                
In [3]: pol.adjust({"II_em": [{"year": 2017, "value": 2000}]}) …
```

Drop warnings for adjusting non-active values.

---

paramtools/exceptions.py
paramtools/parameters.py
paramtools/select.py
paramtools/tests/test_parameters.py
paramtools/tests/test_select.py

This PR adds a function for selecting parameter values based on a label value being less than some other value:
```python
In [1]: from paramtools import Parameters                                                                                                                                                     
In [2]: class Params(Parameters): 
...:     defaults = { 
...:         "schema": { 
...:             "labels": { 
...:                 "d0": {"type": "int"}, 
...:                 "d1": { 
...:                     "type": "str", 
...:                     "validators": { 
...:                         "choice": {"choices": ["hello", "world"]} 
...:                     }, 
...:                 }, 
...:             } 
...:         }, 
...:         "param": { 
...:             "title": …
```

Add select less than function

---

paramtools/contrib/fields.py
paramtools/schema.py
paramtools/tests/test_parameters.py

This PR makes it so that floats are not casted to integers. For example, if a parameter's value indicates an age cut-off, then a user attempting to set the value to a float is probably confused about the meaning of the parameter. So, raising an error here could be helpful for the user.
cc @Peter-Metz

Update int field so that floats are invalid

---

paramtools/contrib/fields.py
paramtools/tests/defaults.json
paramtools/tests/test_parameters.py

Resolves bug found by @Peter-Metz: https://github.com/PSLmodels/Tax-Calculator/pull/2401#discussion_r409622984

Fix bug where errors weren't raised on non-list params

---

docs/Extend example.ipynb
docs/docs/api/extend.md
docs/docs/api/indexing.md
paramtools/__init__.py
paramtools/exceptions.py
paramtools/parameters.py
paramtools/schema.py
paramtools/schema_factory.py
paramtools/select.py
paramtools/tests/test_parameters.py
paramtools/tests/test_select.py
paramtools/tests/test_tree.py
paramtools/tree.py
paramtools/utils.py

PT can automatically extend parameter values using the the label `label_to_extend` and its range of possible values. This PR adds an attribute to each value object that is added automatically. It could be helpful to know which values are added automatically and which are set for a specific reason:
```python
In [1]: from taxcalc import Policy                                                                                                                                                            
In [2]: pol = Policy()                                                                                                                                                                        
In [3]: pol.STD …
```

Add internal attribute on all extend values

---

paramtools/parameters.py
paramtools/tests/test_parameters.py

Fixes bug where the user isn't able to revert an ops argument back to the default value:
```python
class Params3(Parameters):
array_first = True
defaults = {"schema": {"operators": {"array_first": True}}}
params = Params3(array_first=False)
```

Fix case where overriding class attr to use default

---

docs/docs/api/reference.md
paramtools/contrib/fields.py
paramtools/contrib/validate.py
paramtools/exceptions.py
paramtools/parameters.py
paramtools/select.py
paramtools/tests/test_fields.py
paramtools/tests/test_parameters.py

- Updates for edge cases in extend logic when directly using the `extend` method and setting `label_to_extend_values`.
- Case 1: `label_to_extend values` is an empty list:
```python
params = ExtParams()
init = params.select_eq("extend_param")
params.extend(label_to_extend="d0", label_to_extend_values=[])
assert init == params.select_eq("extend_param")
```
- Case 2: `label_to_extend_values` are all values greater than the defined values:
```python
params = ExtParams()
params.extend(label_to_extend="d0", label_to_extend_values=[8, 9, 10])
params.sort_values()
assert params.extend_param == [
{"d0": 2, "d1": "c1", "value": 1},
{"d0": 2, "d1": "c2", "value": 2},
{"d0": 3, "d1": "c1", "value": 3},
{"d0": 3, "d1": "c2", "value": 4},
{"d0": 5, "d1": "c1", "value": 5},
{"d0": 5, "d1": "c2", …
```

Fixes to extend logic and label validation

---

paramtools/parameters.py
paramtools/tests/test_parameters.py

This PR fixes a few bugs relating to the `sort_values` method.
Thanks for the bug report @Peter-Metz.
This should be the last PR before the next PT release.

Fix sort_values bugs relating to in-memory operations and instance state

---

paramtools/__init__.py
paramtools/parameters.py
paramtools/schema.py
paramtools/tests/test_parameters.py
paramtools/tests/test_utils.py
paramtools/utils.py

This PR:
- Simplifies the process for finding the "closest" value to extend from in the `extend` method. The key insight is that the value to extend from is the one with the label-to-extend value being closest to the current missing value with a a preference towards that value being less than the missing value.
- Implements a basic sorted key list data structure for finding the closest value. This was inspired by [Sorted Containers](http://www.grantjenks.com/docs/sortedcontainers/) and the [`bisect` module docs](https://docs.python.org/3.9/library/bisect.html).
- Bypasses deserialization when using the `extend` method. Deserialization isn't needed because the values that are being passed to `_adjust` are pulled from the already deserialized data in `_data`. This saves a considerable chunk …

Minor readability and performance improvements for extend method

---

paramtools/contrib/fields.py

This fixes the following deserialization bug:
```
File "make_uguide.py", line 84, in reformat_params
params = pol.specification(serializable=True)
File "/home/hankdoupe/Documents/ParamTools/paramtools/parameters.py", line 500, in specification
ser = self._defaults_schema.dump(all_params)
File "/home/hankdoupe/miniconda3/envs/taxcalc-dev/lib/python3.8/site-packages/marshmallow/schema.py", line 556, in dump
result = self._serialize(processed_obj, many=many)
File "/home/hankdoupe/miniconda3/envs/taxcalc-dev/lib/python3.8/site-packages/marshmallow/schema.py", line 520, in _serialize
value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
File "/home/hankdoupe/miniconda3/envs/taxcalc-dev/lib/python3.8/site-packages/marshmallow/fields.py", line 311, in serialize
return …
```

Fix bug when value (maybe) has already been deserialized

---

environment.yml

```
(base) mghenis@penguin:~/ParamTools$ conda env create
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
```

Add pip to environment.yml to avoid warning

---

environment.yml
paramtools/__init__.py
paramtools/parameters.py
paramtools/tests/test_utils.py
paramtools/typing.py
paramtools/utils.py
setup.py

- Add `fsspec` to read many types of files. This makes it easy to add support for:
- s3 files: s3://paramtools-test/defaults.json
- google cloud storage files: gs://cs-inputs-dev/defaults.json
- http files: https://raw.githubusercontent.com/PSLmodels/ParamTools/master/paramtools/tests/defaults.json
- files on github: github://PSLmodels:ParamTools@master/paramtools/tests/defaults.json
- Improves error messages and error handling for invalid data:
**Invalid JSON String:**
```
In [2]: read_json('{"hello": "world"')                                                                                                                                                        
---------------------------------------------------------------------------
JSONDecodeError                           Traceback …
```

Read more file sources

---

paramtools/parameters.py
paramtools/schema.py
paramtools/schema_factory.py

This PR fixes the order for:
- schema vs other parameter names when using `params.dump()`
- exposes the `use_state` kwarg to easily dump without having to run `params.clear_state()` beforehand. 
- makes the value objects ordered by having their marshmallow schema inherit from `OrderedSchema`
cc @Peter-Metz

Fix attribute order when dumping parameters to JSON

---

paramtools/exceptions.py
paramtools/parameters.py
paramtools/tests/test_parameters.py

This fixes a bug that occurs when you update an operator attribute like `array_first` after creating the `Parameters` instance and then call `dump`. The "schema" object returned will not have the updated operators. 
Before:
```python
In [1]: from paramtools import Parameters
In [2]: class Params(Parameters):
...:     defaults = {"schema": {"operators": {"array_first": True}}}
...: 
In [3]: params = Params()
In [4]: params.array_first = False
In [5]: params.dump()
Out[5]: 
{'schema': {'labels': {},
'operators': {'label_to_extend': None,
'uses_extend_func': False,
'array_first': True},                          # <=== this should be False!
'additional_members': {}}}
```
After fix:
```python
In [1]: from paramtools import Parameters
In [2]: class Params(Parameters):
...:     defaults = …
```

Check for changes to operator attributes when getting the schema

---

paramtools/tests/test_utils.py
paramtools/utils.py

Allow comments in JSON file like:
```json
// this is my json file
// more comments here
/*
multi line comments?
*/
{
"hello": "world",
"allows_urls": "http://double-slash-is-ok.com"
}
```
```python
In [1]: import paramtools                                                           
In [2]: s = """// this is my json file 
...: // more comments here 
...: /* 
...: multi line comments? 
...: */ 
...: { 
...:     "hello": "world", 
...:     "allows_urls": "http://double-slash-is-ok.com" 
...: }"""                                                                        
In [3]: paramtools.read_json(s)                                                     
Out[3]: 
OrderedDict([('hello', 'world'),
('allows_urls', 'http://double-slash-is-ok.com')])
```

Allow json comments

---

paramtools/schema.py
paramtools/tests/test_parameters.py

Fixes this bug:
```
def validate_param(self, param_name, param_spec, raw_data):
"""
Do range validation for a parameter.
"""
validate_schema = not getattr(
self.context["spec"], "_defer_validation", False
)
validators = self.validators(
param_name, param_spec, raw_data, validate_schema=validate_schema
)
warnings = []
errors = []
for validator in validators:
try:
>               validator(param_spec, is_value_object=True)
E               TypeError: 'NoneType' object is not callable
paramtools/schema.py:283: TypeError
```

Fix bug with defer_validation and when validator interaction

---

.github/workflows/test.yml
paramtools/schema.py

This PR updates calls to `marshmallow.fields` to use the `load_defaults` kwarg rather than the deprecated `missing` kwarg.
Addresses Issue #133.

Use `load_defaults` rather than `missing`

---

docs/_toc.yml
setup.py

This PR makes two small updates:
1. It includes the version number in `setup.py`, so when the package is built, it has the current version number.
2. The table of contents for the JupyterBook documentation is updated to work with the latest version of JB.

Update to TOC for documentation, `setup.py`

---

paramtools/__init__.py
paramtools/exceptions.py
paramtools/parameters.py
paramtools/schema_factory.py
paramtools/tests/test_parameters.py

@jdebacker , let me know if this works for you. You can override the `get_defaults` class in `taxcalc.Parameters` and change this value in the JSON to use the new last year value.
https://github.com/PSLmodels/Tax-Calculator/blob/b41af537803488b6ac40beb0a0e0a7e81cfb6dbd/taxcalc/policy_current_law.json#L9

Add get_defaults method to allow sub-class to customize parameter loading
